global:
  smtp_smarthost: "lnmail:25"
  smtp_from: "lnsystems@litinow.dev"
  smtp_require_tls: false

route:
  receiver: "email-notifications"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2h

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "lnsystems@litinow.dev"
        send_resolved: true
